name: ${PROJECT_NAME}

services:
  hub:
    build: ./services/hub
    ports:
      - "${HUB_PORT}:80"
    networks:
      - public_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  pivot:
    build: ./services/pivot
    networks:
      - public_net
      - internal_net
    restart: unless-stopped
    healthcheck:
        test: ["CMD-SHELL", "wget -qO- http://localhost/ >/dev/null 2>&1 || exit 1"]
        interval: 10s
        timeout: 3s
        retries: 5
        start_period: 5s

  cctv:
    build: ./services/cctv
    networks:
      - internal_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    
  vault:
    build: ./services/vault
    networks:
      - internal_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
  
  alarm:
    build: ./services/alarm
    networks:
      - internal_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  blacktide_vuln:
    image: vulnerables/web-dvwa
    networks:
      - public_net
    restart: unless-stopped

  blacktide_gateway:
    build: ./services/blacktide-gateway
    ports:
      - "${PIVOT_PORT}:80"
    networks:
      - public_net
    restart: unless-stopped
    depends_on:
      - blacktide_vuln
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s


networks:
  public_net:
    driver: bridge
  internal_net:
    driver: bridge